# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup_env:
    uses: ./.github/workflows/reusable.yml

  set_short_sha:
    runs-on: ubuntu-latest
    outputs: 
      SHORT_SHA: ${{ steps.set-short-sha.outputs.SHORT_SHA }}
    steps:
      - run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
          echo env.SHORT_SHA
      - id: set-short-sha
        run: echo "::set-output name=SHORT_SHA::$SHORT_SHA"

  another_job:
    runs-on: ubuntu-latest
    needs: setup_env
    steps:
      - run: echo "FIRST_WORD=${{ needs.setup_env.outputs.secret_firstword }}" >> $GITHUB_ENV

  yet_another_job:
    runs-on: ubuntu-latest
    needs: [another_job, set_short_sha]
    
    steps:
      - name: some step
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo ${{ env.FIRST_WORD }}
      - name: dump github context
        run: echo $GITHUB_CONTEXT
      - name: dump SHORT_SHA
        run: echo ${{ needs.set_short_sha.outputs.SHORT_SHA }}
      - name: dump github ref name
        run: echo $GITHUB_REF_NAME
