name: Setup

on:
  workflow_call:
    outputs:
    firstword:
      description: "The first output string"
      value: ${{ jobs.example_job.outputs.output1 }}
    secondword:
      description: "The second output string"
      value: ${{ jobs.example_job.outputs.output2 }}


jobs:
  setup_env_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment Variables
        run: echo "FOO=bar" >> $GITHUB_ENV
      - name: Print Environment Variables
        run: echo ${{ env.FOO }}
      - id: step2
        run: echo "::add-mask name=secondword::${{ env.FOO }}"