name: Setup

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      secondword:
        description: "The second output string"
        value: ${{ jobs.setup_env_variables.outputs.output2 }}


jobs:
  setup_env_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment Variables
        run: echo "FOO=bar" >> $GITHUB_ENV
      - name: Print Environment Variables
        run: echo ${{ env.FOO }}
      - id: step2
        run: echo "::add-mask name=secondword::$FOO"