name: Setup

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request_target:
    types: [closed]
    branches: [main]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  setup_env_variables:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Environment Variables
        run: echo "FOO=bar" >> $GITHUB_ENV
      - name: Print Environment Variables
        run: echo ${{ env.FOO }}